# Generated by Django 4.0.4 on 2022-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='summary', verbose_name='summary'),
            preserve_default=False,
        ),
    ]
